### ISSUE TITLE
Latest version does not include ES module entry points

### ISSUE THREAD

**Issue by 0f-0b** [esfx/esfx#47]
```shellsession
$ cat package.json
{
  "dependencies": {
    "@esfx/lazy": "1.0.0-pre.33"
  }
}
$ node --input-type=commonjs -e 'require("@esfx/lazy")'
$ node --input-type=module -e 'import "@esfx/lazy"'
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<cwd>/node_modules/@esfx/lazy/dist/esm/index.js' imported from <cwd>/[eval1]
Did you mean to import @esfx/lazy/dist/cjs/index.js?
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:305:11)
    at moduleResolve (node:internal/modules/esm/resolve:866:10)
    at defaultResolve (node:internal/modules/esm/resolve:1074:11)
    at nextResolve (node:internal/modules/esm/loader:164:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:839:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.8.0
```

**Comment by rbuckton** [comment]
Thanks.l for the update. You may want to pin to `.pre.30` or earlier while I work or a few issues.

**Comment by rbuckton** [comment]
This should be fixed in 1.0.0-pre.34

**Comment by 0f-0b** [comment]
Some packages (including `@esfx/disposable`) are still broken because of `dist/cjs/internal` and `dist/esm/internal` being ignored by `.npmignore`. Should I open another issue?

**Comment by rbuckton** [comment]
I just published 1.0.0-pre.36 which hopefully addresses that. If you find any other missing files please let me know. I've added in a prepack script that verifies the file list in each package matches an expected set of files, but I still need to go through a few individual packages and verify the list is accurate.

**Comment by 0f-0b** [comment]
Native code in `@esfx/equatable` does not compile on macOS and all three prebuilt binaries on GitHub are for Windows despite their filenames. `dist/esm/package.json` no longer exists, which causes the files under `dist/esm` to be loaded as CommonJS. [`dist/esm/index.js` in `@esfx/async-waitqueue`](https://unpkg.com/@esfx/async-waitqueue@1.0.0-pre.36/dist/esm/index.js) and several other modules have export declarations inside functions. I believe these are the only issues preventing the packages from being imported now.

**Comment by rbuckton** [comment]
Thanks for the updates. I'll keep iterating on this and will hopefully be able to get this working tomorrow. I may have to temporarily disable the native builds as well until I can get an environment set up to address MacOS and Linux builds.

**Comment by rbuckton** [comment]
Alright, I've published `-pre.37` which should have the missing `package.json` stubs and disables native hash code generation for now.
